#!/bin/bash

# PM2 Management Commands for IQX Backend

echo "PM2 Management Commands for IQX Backend"
echo "========================================"
echo ""
echo "Available commands:"
echo ""
echo "1. Start production:"
echo "   pm2 start ecosystem.config.js --env production"
echo ""
echo "2. Start development:"
echo "   pm2 start ecosystem.config.js --env development"
echo ""
echo "3. Stop:"
echo "   pm2 stop iqx-backend"
echo ""
echo "4. Restart:"
echo "   pm2 restart iqx-backend"
echo ""
echo "5. Reload (zero-downtime):"
echo "   pm2 reload iqx-backend"
echo ""
echo "6. View logs:"
echo "   pm2 logs iqx-backend"
echo ""
echo "7. View logs (last 100 lines):"
echo "   pm2 logs iqx-backend --lines 100"
echo ""
echo "8. Monitor:"
echo "   pm2 monit"
echo ""
echo "9. Status:"
echo "   pm2 status"
echo ""
echo "10. Delete from PM2:"
echo "    pm2 delete iqx-backend"
echo ""
echo "11. Save PM2 config:"
echo "    pm2 save"
echo ""
echo "12. Setup startup script:"
echo "    pm2 startup"
echo ""
echo "13. View process details:"
echo "    pm2 show iqx-backend"
echo ""
echo "14. Flush logs:"
echo "    pm2 flush iqx-backend"
echo ""
echo "========================================"